; Sprite mappings - generated by Flex - Sonic 1 format

@Mapping:
	dc.w	@Frame0-@Mapping, @Frame1-@Mapping
	dc.w	@Frame2-@Mapping, @Frame3-@Mapping
	dc.w	@Frame4-@Mapping

@Frame0:
	dc.b  1
	dc.b  $F4, $1, $0, $1, $FC
	even
@Frame1:
	dc.b  1
	dc.b  $FC, $0, $0, $0, $FC
	even
@Frame2:
	dc.b  1
	dc.b  $F4, $1, $0, $3, $FC
	even
@Frame3:
	dc.b  1
	dc.b  $F4, $1, $8, $3, $FB
	even
@Frame4:
	dc.b  1
	dc.b  $FC, $0, $0, $5, $FC
	even
